// Copyright [2020] [Banana.ch SA - Lugano Switzerland]
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
/* Last update: 2020-12-08 */
var num=1,ERROR_READING_BANANA=!1,ERROR_CONNECTION=!1,SUBSTRING_FILE_NAME_TEST="_test_expected",BANANA_VERSION="",RANGE_QUERYACCOUNT="A16:A100000",RANGE_WORKSHEET="A2:AZ100000",EXCEL_COLUMNS="A B C D E F G H I J K L M N O P Q R S T U V W X Y Z AA AB AC AD AE AF AG AH AI AJ AK AL AM AN AO AP AQ AR AS AT AU AV AW AX AY AZ".split(" "),settingsStorage=window.localStorage,settings={settingsServerUrl:"",settingsLanguage:""};
function httpGet(a){try{var b=settings.settingsServerUrl;b=""===b||null==b?"https://127.0.0.1:8089/v1/":b+"/v1/";var c="";c=-1<a.indexOf("?")?b+a+"&"+num:b+a+"?"+num;var f=new XMLHttpRequest;f.open("GET",c,!1);f.send(null);num++;return f.responseText}catch(e){return null}}function applicationInfo(a){return httpGet("application/"+a)}function info(a,b,c){return httpGet("doc/"+a+"/info/"+b+"/"+c)}
function accountDescription(a,b,c){"Account"===c?(c=httpGet("doc/"+a+"/accountdescription/"+b+"/Account"),""===c&&(c=httpGet("doc/"+a+"/accountdescription/"+b+"/Category"))):"Category"===c?(c=httpGet("doc/"+a+"/accountdescription/"+b+"/Category"),""===c&&(c=httpGet("doc/"+a+"/accountdescription/"+b+"/Account"))):c=httpGet("doc/"+a+"/accountdescription/"+b+"/"+c);return c}function currentBalance(a,b,c){a=httpGet("doc/"+a+"/balance/"+b+"/?period="+c+"&format=json");return JSON.parse(a)}
function budgetBalance(a,b,c){a=httpGet("doc/"+a+"/budget/"+b+"/?period="+c+"&format=json");return JSON.parse(a)}function startperiod(a,b){return"ALL"===b?httpGet("doc/"+a+"/startperiod?period"):httpGet("doc/"+a+"/startperiod?period="+b)}function endperiod(a,b){return"ALL"===b?httpGet("doc/"+a+"/endperiod?period"):httpGet("doc/"+a+"/endperiod?period="+b)}function vatCurrentBalance(a,b,c){a=httpGet("doc/"+a+"/vatbalance/"+b+"/?period="+c+"&format=json");return JSON.parse(a)}
function vatDescription(a,b,c){return httpGet("doc/"+a+"/vatdescription/"+b+"/"+c)}function tableAccounts(a){a=httpGet("doc/"+a+"/table/Accounts?format=json");return JSON.parse(a)}function tableVatCodes(a){a=httpGet("doc/"+a+"/table/VatCodes?format=json");return JSON.parse(a)}function columnNames(a,b){return httpGet("doc/"+a+"/table/"+b+"/columnnames")}
function log(a,b){var c=new Date,f=c.getDate(),e=c.getMonth()+1,d=c.getFullYear(),g=c.getHours(),k=c.getMinutes();c=c.getSeconds();9>=f&&(f="0"+f);9>=e&&(e="0"+e);9>=g&&(g="0"+g);9>=k&&(k="0"+k);9>=c&&(c="0"+c);f=g+":"+k+":"+c+", "+f+"."+e+"."+d;if(1==b)var l="https://raw.githubusercontent.com/BananaAccounting/General/master/OfficeAddIns/ExcelAddIns/BananaAccounting/msofficeplugin_local/images/message_info.png";else 2==b&&(l="https://raw.githubusercontent.com/BananaAccounting/General/master/OfficeAddIns/ExcelAddIns/BananaAccounting/msofficeplugin_local/images/message_error.png");e=document.getElementById("textarea");e.insertAdjacentHTML("beforeend","<div>"+f+"</div>");e.insertAdjacentHTML("beforeend",'<div><img style="vertical-align:middle;" src='+
l+"> "+a+"</div>");e.insertAdjacentHTML("beforeend","<p></p>")}function testlog(a){document.getElementById("textarea").insertAdjacentHTML("beforeend","<div>"+a+"</div>")}function openConfirm(){document.getElementById("confirmationModal").style.display="block"}function confirmationAnswer(a){a&&(setSettings(),setUrlPort(),document.location.reload(!0));document.getElementById("confirmationModal").style.display="none";app.closeConfirmation()}
function setSettings(){var a=$("#slctServerUrl").val();"urlOther"===a?""===document.getElementById("settingsServerUrl").value||null==document.getElementById("settingsServerUrl").value?settings.settingsServerUrl="https://127.0.0.1:8089":settings.settingsServerUrl=document.getElementById("settingsServerUrl").value:"urlDefault1"===a?settings.settingsServerUrl="https://127.0.0.1:8089":"urlDefault2"===a&&(settings.settingsServerUrl="https://banana.localhost:8089");settings.settingsLanguage=document.getElementById("settingsLanguage").value;
settingsStorage.setItem("settingsServerUrl",settings.settingsServerUrl);settingsStorage.setItem("settingsLanguage",settings.settingsLanguage)}
function getSettings(){settings.settingsServerUrl=settingsStorage.getItem("settingsServerUrl");settings.settingsLanguage=settingsStorage.getItem("settingsLanguage");"https://127.0.0.1:8089"===settings.settingsServerUrl?document.getElementById("slctServerUrl").value="urlDefault1":"https://banana.localhost:8089"===settings.settingsServerUrl?document.getElementById("slctServerUrl").value="urlDefault2":(document.getElementById("slctServerUrl").value="urlOther",document.getElementById("server-url-token").style.display=
"block");document.getElementById("settingsServerUrl").value=settings.settingsServerUrl;document.getElementById("settingsLanguage").value=settings.settingsLanguage}function checkErrors(){ERROR_CONNECTION=ERROR_READING_BANANA=!1;try{0<JSON.parse(httpGet("docs")).length?ERROR_CONNECTION=ERROR_READING_BANANA=!1:ERROR_READING_BANANA=!0}catch(a){ERROR_CONNECTION=!0}}
(function(){Office.initialize=function(a){$(document).ready(function(){app.initialize();getSettings();var a=UIStrings.getLocaleStrings(""===settings.settingsLanguage||null==settings.settingsLanguage||"excelPredefined"===settings.settingsLanguage?Office.context.displayLanguage:settings.settingsLanguage);setLocalizedText(a);$("#update-list").click(getFileNamesList);$("#load-data").click(generateWorksheetContent);$("#slctType").change(loadColumnOptions);$("#slctFile").change(getSegments);$("#load-all-column").click(addValuesNewColumn);
$("#slctDateStart").change(getPeriodDate);$("#add_to_query_options").click(loadQueryOption);$("#update-data").click(updateTables);$("#create-test-current").click(createTestCurrent);$("#create-test-all").click(createTestAll);$("#test-data").click(test);$("#slct1").change(populate);$("#add_to_query_account").click(addToQueryAccount);$("#delete-all").click(deleteActiveWorksheet);$("#settings-url").click(setUrlPort);$("#add-header-options").click(addHeaderOptions)})}})();
function setLocalizedText(a){$("#defaultOpen").text(a.strSetup);$("#update").text(a.strUpdate);$("#test").text(a.strTest);$("#logs").text(a.strLogs);$("#dev").text(a.strDev);$("#help").text(a.strHelp);$("#titleSetup").text(a.strTitleSetup);$("#bananaFile").text(a.strBananaFile);$("#update-list").text(a.strUpdateList);$("#setHeader").text(a.strSetHeader);$("#selectHeader").text(a.strSelectHeader);$("#predefinedHeader").text(a.strPredefinedHeader);$("#emptyHeader").text(a.strEmptyHeader);$("#load-data").text(a.strAddHeader);
$("#textHeaderOptions").text(a.strTextHeaderOptions);$("#selectOptionCurrency").text(a.strSelectOptionCurrency);$("#selectOptionHeaderLeft").text(a.strSelectOptionHeaderLeft);$("#selectOptionHeaderRight").text(a.strSelectOptionHeaderRight);$("#repeatCurrency").text(a.strRepeatCurrency);$("#norepeatCurrency").text(a.strNoRepeatCurrency);$("#repeatHeaderLeft").text(a.strRepeatHeaderLeft);$("#norepeatHeaderLeft").text(a.strNoRepeatHeaderLeft);$("#repeatHeaderRight").text(a.strRepeatHeaderRight);$("#norepeatHeaderRight").text(a.strNoRepeatHeaderRight);
$("#add-header-options").text(a.strAddHeaderOptions);$("#setQueryColumns").text(a.strSetQueryColumns);$("#textSetQueryColumns").text(a.strTextSetQueryColumns);$("#slctSheetColumn").text(a.strSlctSheetColumn);$("#optSelectAnOption").text(a.strOptSelectAnOption);$("#selectedColumn").text(a.strSelectedColumn);$("#slctFilename").text(a.strSlctFilename);$("#optSelectAnOptionFile").text(a.strOptSelectAnOptionFile);$("#currentFile").text(a.strCurrentFile);$("#currentVoid").text(a.strCurrentVoid);$("#p1").text(a.strP1);
$("#p2").text(a.strP2);$("#p3").text(a.strP3);$("#slctTypeValue").text(a.strSlctTypeValue);$("#optSelectAnOptionType").text(a.strOptSelectAnOptionType);$("#slctColumnValue").text(a.strSlctColumnValue);$("#optSelectAnOptionColumn").text(a.strOptSelectAnOptionColumn);$("#slctSegmentValue").text(a.strSlctSegmentValue);$("#optSelectAnOptionSegment").text(a.strOptSelectAnOptionSegment);$("#slctPeriodValue").text(a.strSlctPeriodValue);$("#allVoid").text(a.strAllVoid);$("#customDate").text(a.strCustomDate);
$("#M1").text(a.strM1);$("#M2").text(a.strM2);$("#M3").text(a.strM3);$("#M4").text(a.strM4);$("#M5").text(a.strM5);$("#M6").text(a.strM6);$("#M7").text(a.strM7);$("#M8").text(a.strM8);$("#M9").text(a.strM9);$("#M10").text(a.strM10);$("#M11").text(a.strM11);$("#M12").text(a.strM12);$("#Q1").text(a.strQ1);$("#Q2").text(a.strQ2);$("#Q3").text(a.strQ3);$("#Q4").text(a.strQ4);$("#S1").text(a.strS1);$("#S2").text(a.strS2);$("#Y1").text(a.strY1);$("#Y2").text(a.strY2);$("#load-all-column").text(a.strLoadAllColumn);
$("#setQueryAccounts").text(a.strSetQueryAccounts);$("#addAccounts").text(a.strAddAccounts);$("#optSelectAnOptionAccounts").text(a.strOptSelectAnOptionAccounts);$("#add_to_query_account").text(a.strAddToQueryAccount);$("#qaAccounts").text(a.strQaAccounts);$("#qaGroups").text(a.strQaGroups);$("#qaCostCenters").text(a.strQaCostCenters);$("#qaSegments").text(a.strQaSegments);$("#qaAll").text(a.strQaAll);$("#qaVatCodes").text(a.strQaVatCodes);$("#select-all").text(a.strSelectAll);$("#qaOptions").text(a.strQaOptions);
$("#optSelectAnOptionOptions").text(a.strOptSelectAnOptionOptions);$("#invert").text(a.strInvert);$("#budget").text(a.strBudget);$("#budgetinvert").text(a.strBudgetinvert);$("#add_to_query_options").text(a.strAddToQueryOptions);$("#titleUpdate").text(a.strTitleUpdate);$("#textUpdate").text(a.strTextUpdate);$("#update-data").text(a.strUpdateData);$("#titleSettings").text(a.strTitleSettings);$("#insertPort").text(a.strInsertPort);$("#excelPredefined").text(a.strExcelPredefined);$("#changeLanguage").text(a.strChangeLanguage);
$("#serverInformation").text(a.strServerInformation);$("#insertServerUrl").text(a.strInsertServerUrl);$("#insertPort").text(a.strInsertPort);$("#insertToken").text(a.strInsertToken);$("#defaultUrl").text(a.strDefaultUrl);$("#urlOther").text(a.strUrlOther);$("#options").text(a.strOptions);$("#confirmation-message-header").text(a.strConfirmationMessageHeader);$("#confirmation-message-body").text(a.strConfirmationMessageBody);$("#confirmation-message-body2").text(a.strConfirmationMessageBody2);$("#confirm-yes").text(a.strConfirmYes);
$("#confirm-no").text(a.strConfirmNo)}
function addHeaderOptions(){app.clearNotification();var a=$("#slctQueryOptionCurrency").val(),b=$("#slctQueryOptionHeaderLeft").val(),c=$("#slctQueryOptionHeaderRight").val();Excel.run(function(f){return f.sync().then(function(){f.workbook.worksheets.getActiveWorksheet().getRange("B11").values=a;f.workbook.worksheets.getActiveWorksheet().getRange("B12").values=b;f.workbook.worksheets.getActiveWorksheet().getRange("B13").values=c})})["catch"](function(a){log(a,2)})}
function addValuesNewColumn(){app.clearNotification();var a=$("#slctColumnIndex").val(),b=$("#ListBox").val(),c=$("#slctFile").val(),f=$("#slctType").val(),e=$("#slctColumn").val(),d=$("#slctSegment").val();d=""!==d?d.split(" ")[0]:"";var g=$("#slctDateStart").val();Excel.run(function(k){var l=k.workbook.getSelectedRange().load();return k.sync().then(function(){if("selectedColumn"===a){var n=l.address.split("!")[1];a=-1<n.indexOf(":")?n.split(":")[0]:n.match(/([A-Za-z]+)([0-9]+)/)[1]}if("A"!==a&&
"B"!==a&&("current"===c?k.workbook.worksheets.getActiveWorksheet().getRange(a+"3").values=b:"currentVoid"===c?k.workbook.worksheets.getActiveWorksheet().getRange(a+"3").values="":k.workbook.worksheets.getActiveWorksheet().getRange(a+"3").values=c,k.workbook.worksheets.getActiveWorksheet().getRange(a+"4").values=f,k.workbook.worksheets.getActiveWorksheet().getRange(a+"5").values=e,"Current"===f||"Budget"===f||"CurrentVat"===f))if(k.workbook.worksheets.getActiveWorksheet().getRange(a+"6").values=d,
"CustomDate"===g){n=$("#start-date-input").val();var m=$("#end-date-input").val();k.workbook.worksheets.getActiveWorksheet().getRange(a+"7").values=n;k.workbook.worksheets.getActiveWorksheet().getRange(a+"8").values=m}else k.workbook.worksheets.getActiveWorksheet().getRange(a+"7").values=g})})["catch"](function(a){log(a,2)})}
function getSegments(){$("#slctSegment").empty();var a=$("#slctFile").val();a="current"===a||"currentVoid"===a?$("#ListBox").val():$("#ListBox").val()+"_"+a;var b=document.getElementById("slctSegment");var c=document.createElement("option");c.text="";b.add(c);a=loadSegments(a);var f=a.length;if(0<f)for(var e=0;e<f;e++)b=document.getElementById("slctSegment"),c=document.createElement("option"),c.text=a[e],b.add(c)}
function loadQueryOption(){app.clearNotification();var a=$("#slctQueryOptions").val();Excel.run(function(b){var c=b.workbook.getSelectedRange().load();return b.sync().then(function(){var f=c.address.split("!")[1].match(/([A-Za-z]+)([0-9]+)/),e=f[1];f=f[2];"15"<f&&"B"===e?(b.workbook.worksheets.getActiveWorksheet().getRange(e+f).values=a,b.workbook.worksheets.getActiveWorksheet().getRange(e+f).select()):(e=document.getElementById("settingsLanguage").value,"excelPredefined"===e&&(e=Office.context.displayLanguage),
"it-IT"===e?app.showNotification("Cella sbagliata. La cella deve essere nella colonna 'QueryOptions' dalla riga 16 in avanti."):"de-DE"===e?app.showNotification("Falsche Zelle. Die Zelle muss in Spalte 'QueryOptions' von Zeile 16 vorw\u00e4rts sein."):"fr-FR"===e?app.showNotification("Mauvaise cellule. La cellule doit \u00eatre dans la colonne 'QueryOptions' de la ligne 16 vers l'avant."):app.showNotification("Wrong cell. The cell must be in column 'QueryOptions' at any row from the 16 forward."))})})["catch"](function(a){log(a,
2)})}function getPeriodDate(){"CustomDate"===$("#slctDateStart").val()?document.getElementById("custom-period").style.display="block":document.getElementById("custom-period").style.display="none"}
function loadColumnOptions(){document.getElementById("slctSegment").disabled=!1;document.getElementById("slctDateStart").disabled=!1;$("#slctColumn").empty();var a=$("#ListBox").val(),b=$("#slctType").val();if("Column"===b){var c=columnNames(a,"Accounts");c=c.replace("[","");c=c.replace("]","");c=c.split(",");a=c.length;if(0<a)for(b=0;b<a;b++){var f=document.getElementById("slctColumn"),e=document.createElement("option");e.text=c[b];f.add(e)}document.getElementById("slctSegment").disabled=!0;document.getElementById("slctDateStart").disabled=
!0;document.getElementById("custom-period").style.display="none"}else if("Current"===b||"Budget"===b)for(c="amount amountcurrency balance balancecurrency bclass credit creditcurrency debit debitcurrency enddate opening openingcurrency periodstring rowcount startdate total totalcurrency".split(" "),a=c.length,b=0;b<a;b++)f=document.getElementById("slctColumn"),e=document.createElement("option"),e.text=c[b],f.add(e);else if("ColumnVat"===b){c=columnNames(a,"VatCodes");c=c.replace("[","");c=c.replace("]",
"");c=c.split(",");a=c.length;if(0<a)for(b=0;b<a;b++)f=document.getElementById("slctColumn"),e=document.createElement("option"),e.text=c[b],f.add(e);document.getElementById("slctSegment").disabled=!0;document.getElementById("slctDateStart").disabled=!0;document.getElementById("custom-period").style.display="none"}else if("CurrentVat"===b)for(c=["taxable","amount","notdeductible","posted","rowcount"],a=c.length,b=0;b<a;b++)f=document.getElementById("slctColumn"),e=document.createElement("option"),
e.text=c[b],f.add(e)}function changeUrl(){"urlOther"===$("#slctServerUrl").val()?document.getElementById("server-url-token").style.display="block":document.getElementById("server-url-token").style.display="none"}function setUrlPort(){var a=settings.settingsServerUrl;document.getElementById("settingsToken");""===a||null==a?log("Server information changed to default 'https://127.0.0.1:8089'",1):log("Server information changed to '"+a+"'",1)}
function getFileNamesList(){app.clearNotification();$("#ListBox").empty();var a=settings.settingsLanguage;checkErrors();if(ERROR_CONNECTION){var b=document.getElementById("ListBox"),c=document.createElement("option");c.text="<FILENAME>";b.add(c);"excelPredefined"===a&&(a=Office.context.displayLanguage);"it-IT"===a?(app.showNotificationError("Impossibile connettersi al web server locale. Server URL non corretto o Banana Contabilit\u00e0/web server non in esecuzione."),log("Impossibile connettersi al web server locale. Server URL non corretto o Banana Contabilit\u00e0/web server non in esecuzione.",
2)):"de-DE"===a?(app.showNotificationError("Verbindung zum lokalen Webserver kann nicht hergestellt werden. Falscher URL-Server oder Banana Buchhaltung/Webserver nicht ausgef\u00fchrt."),log("Verbindung zum lokalen Webserver kann nicht hergestellt werden. Falscher URL-Server oder Banana Buchhaltung/Webserver nicht ausgef\u00fchrt.",2)):"fr-FR"===a?(app.showNotificationError("Impossible de se connecter au serveur web local. Serveur URL incorrect ou Banana Comptabilit\u00e9/serveur web ne fonctionnent pas."),
log("Impossible de se connecter au serveur web local. Serveur URL incorrect ou Banana Comptabilit\u00e9/serveur web ne fonctionnent pas.",2)):(app.showNotificationError("Cannot connect to local web server. Incorrect URL server or Banana Accounting/web server are not running."),log("Cannot connect to local web server. Incorrect URL server or Banana Accounting/web server are not running.",2))}else if(BANANA_VERSION=applicationInfo("version"),"9"===BANANA_VERSION.substring(0,1)){var f=JSON.parse(httpGet("docs")),
e=f.length;if(0<e)for(a=0;a<e;a++)b=document.getElementById("ListBox"),c=document.createElement("option"),c.text=f[a],b.add(c);else b=document.getElementById("ListBox"),c=document.createElement("option"),c.text="<FILENAME>",b.add(c),"excelPredefined"===a&&(a=Office.context.displayLanguage),"it-IT"===a?app.showNotificationError("Nessun file aperto in Banana 9."):"de-DE"===a?app.showNotificationError("Keine offene Datei in Banana 9."):"fr-FR"===a?app.showNotificationError("Aucun fichier n'est ouvert dans Banana 9."):
app.showNotificationError("No file is open in Banana 9.")}}
function populate(){app.clearNotification();var a=$("#ListBox").val(),b=document.getElementById("slct1"),c=document.getElementById("slct2");c.innerHTML="";if("Accounts"===b.value){var f=loadAccountsAndCategories(a);document.getElementById("select-all").checked=!1;document.getElementById("select-all-div").style.display="block"}else"Groups"===b.value?(f=loadGroupsOfAccountsAndCategories(a),document.getElementById("select-all").checked=!1,document.getElementById("select-all-div").style.display="block"):
"CostCenters"===b.value?(f=loadCostCenters(a),document.getElementById("select-all").checked=!1,document.getElementById("select-all-div").style.display="block"):"Segments"===b.value?(f=loadSegments(a),document.getElementById("select-all").checked=!1,document.getElementById("select-all-div").style.display="block"):"All"===b.value?(f=loadAll(a),document.getElementById("select-all").checked=!1,document.getElementById("select-all-div").style.display="block"):"VatCodes"===b.value?(f=loadVatCodes(a),document.getElementById("select-all").checked=
!1,document.getElementById("select-all-div").style.display="block"):""===b.value&&(document.getElementById("select-all").checked=!1,document.getElementById("select-all-div").style.display="none");for(var e in f)f.hasOwnProperty(e)&&(a=f[e],b=document.createElement("input"),b.type="checkbox",b.name="checkboxes[]",b.value=a,c.appendChild(b),b=document.createElement("label"),b.htmlFor=a,b.appendChild(document.createTextNode(a)),c.appendChild(b),c.appendChild(document.createElement("br")))}
function loadAccountsAndCategories(a){for(var b=[],c=JSON.parse(httpGet("doc/"+a+"/table/Accounts?format=json")),f=c.length,e=0;e<f;e++)if(c[e].Account){var d=c[e].Account;if("."!==d.substring(0,1)&&","!==d.substring(0,1)&&";"!==d.substring(0,1)&&":"!==d.substring(0,1)&&"::"!==d.substring(0,2)&&":::"!==d.substring(0,3)&&"::::"!==d.substring(0,4)&&":::::"!==d.substring(0,5)&&"::::::"!==d.substring(0,6)&&":::::::"!==d.substring(0,7)&&"::::::::"!==d.substring(0,8)&&":::::::::"!==d.substring(0,9)&&"::::::::::"!==
d.substring(0,10)){var g=c[e].Account;d=c[e].Description;g&&b.push(g+" "+d)}}if("Income & Expense accounting"===info(a,"Base","FileType"))for(a=JSON.parse(httpGet("doc/"+a+"/table/Categories?format=json")),c=a.length,e=0;e<c;e++)a[e].Category&&(d=a[e].Category,"."!==d.substring(0,1)&&","!==d.substring(0,1)&&";"!==d.substring(0,1)&&":"!==d.substring(0,1)&&"::"!==d.substring(0,2)&&":::"!==d.substring(0,3)&&"::::"!==d.substring(0,4)&&":::::"!==d.substring(0,5)&&"::::::"!==d.substring(0,6)&&":::::::"!==
d.substring(0,7)&&"::::::::"!==d.substring(0,8)&&":::::::::"!==d.substring(0,9)&&"::::::::::"!==d.substring(0,10)&&(f=a[e].Category,d=a[e].Description,f&&b.push(f+" "+d)));return b}
function loadGroupsOfAccountsAndCategories(a){for(var b=[],c=JSON.parse(httpGet("doc/"+a+"/table/Accounts?format=json")),f=c.length,e=0;e<f;e++){var d=c[e].Group,g=c[e].Description;d&&b.push("Gr="+d+" "+g)}if("Income & Expense accounting"===info(a,"Base","FileType"))for(a=JSON.parse(httpGet("doc/"+a+"/table/Categories?format=json")),c=a.length,e=0;e<c;e++)d=a[e].Group,g=a[e].Description,d&&b.push("GrC="+d+" "+g);return b}
function loadCostCenters(a){for(var b=[],c=JSON.parse(httpGet("doc/"+a+"/table/Accounts?format=json")),f=c.length,e=0;e<f;e++)if(c[e].Account){var d=c[e].Account;if("."===d.substring(0,1)||","===d.substring(0,1)||";"===d.substring(0,1))d=c[e].Description,b.push(c[e].Account+" "+d)}if("Income & Expense accounting"===info(a,"Base","FileType"))for(a=JSON.parse(httpGet("doc/"+a+"/table/Categories?format=json")),f=a.length,e=0;e<f;e++)a[e].Category&&(d=a[e].Category,"."===d.substring(0,1)||","===d.substring(0,
1)||";"===d.substring(0,1))&&(c=a[e].Category,d=a[e].Description,b.push(c+" "+d));return b}
function loadSegments(a){for(var b=[],c=JSON.parse(httpGet("doc/"+a+"/table/Accounts?format=json")),f=c.length,e=0;e<f;e++)if(c[e].Account){var d=c[e].Account;if(":"===d.substring(0,1)&&":"!==d.substring(1,2)&&""!==d.substring(1,2)||"::"===d.substring(0,2)&&":"!==d.substring(2,3)&&""!==d.substring(2,3)||":::"===d.substring(0,3)&&":"!==d.substring(3,4)&&""!==d.substring(3,4)||"::::"===d.substring(0,4)&&":"!==d.substring(4,5)&&""!==d.substring(4,5)||":::::"===d.substring(0,5)&&":"!==d.substring(5,6)&&
""!==d.substring(5,6)||"::::::"===d.substring(0,6)&&":"!==d.substring(6,7)&&""!==d.substring(6,7)||":::::::"===d.substring(0,7)&&":"!==d.substring(7,8)&&""!==d.substring(7,8)||"::::::::"===d.substring(0,8)&&":"!==d.substring(8,9)&&""!==d.substring(8,9)||":::::::::"===d.substring(0,9)&&":"!==d.substring(9,10)&&""!==d.substring(9,10)||"::::::::::"===d.substring(0,10)&&":"!==d.substring(10,11)&&""!==d.substring(10,11))d=c[e].Description,b.push(c[e].Account+" "+d)}if("Income & Expense accounting"===info(a,
"Base","FileType"))for(c=JSON.parse(httpGet("doc/"+a+"/table/Categories?format=json")),f=c.length,e=0;e<f;e++)c[e].Category&&(d=c[e].Category,":"===d.substring(0,1)&&":"!==d.substring(1,2)&&""!==d.substring(1,2)||"::"===d.substring(0,2)&&":"!==d.substring(2,3)&&""!==d.substring(2,3)||":::"===d.substring(0,3)&&":"!==d.substring(3,4)&&""!==d.substring(3,4)||"::::"===d.substring(0,4)&&":"!==d.substring(4,5)&&""!==d.substring(4,5)||":::::"===d.substring(0,5)&&":"!==d.substring(5,6)&&""!==d.substring(5,
6)||"::::::"===d.substring(0,6)&&":"!==d.substring(6,7)&&""!==d.substring(6,7)||":::::::"===d.substring(0,7)&&":"!==d.substring(7,8)&&""!==d.substring(7,8)||"::::::::"===d.substring(0,8)&&":"!==d.substring(8,9)&&""!==d.substring(8,9)||":::::::::"===d.substring(0,9)&&":"!==d.substring(9,10)&&""!==d.substring(9,10)||"::::::::::"===d.substring(0,10)&&":"!==d.substring(10,11)&&""!==d.substring(10,11))&&(a=c[e].Category,d=c[e].Description,b.push(a+" "+d));return b}
function loadAll(a){for(var b=[],c=JSON.parse(httpGet("doc/"+a+"/table/Accounts?format=json")),f=c.length,e=0;e<f;e++){var d=c[e].Group,g=c[e].Account,k=c[e].Description;g&&b.push(g+" "+k);d&&b.push("Gr="+d+" "+k)}if("Income & Expense accounting"===info(a,"Base","FileType"))for(a=JSON.parse(httpGet("doc/"+a+"/table/Categories?format=json")),c=a.length,e=0;e<c;e++)d=a[e].Group,f=a[e].Category,k=a[e].Description,f&&b.push(f+" "+k),d&&b.push("GrC="+d+" "+k);return b}
function loadVatCodes(a){var b=[];a=JSON.parse(httpGet("doc/"+a+"/vatcodes?format=json"));for(var c=a.length,f=0;f<c;f++)if(a[f].id){var e=a[f].id,d=a[f].descr;e&&b.push(e+" "+d)}return b}
function addToQueryAccount(){app.clearNotification();for(var a=[].filter.call(document.getElementsByName("checkboxes[]"),function(a){return a.checked}).map(function(a){return a.value}),b=[],c=0;c<a.length;c++)b.push(a[c].split(" ")[0]);Excel.run(function(a){var c=a.workbook.getSelectedRange().load();return a.sync().then(function(){var d=c.address.split("!")[1].match(/([A-Za-z]+)([0-9]+)/),e=d[1];d=d[2];if("A"===e){for(var f=0;f<b.length;f++)a.workbook.worksheets.getActiveWorksheet().getRange(e+d).values=
"'"+b[f],d++;a.workbook.worksheets.getActiveWorksheet().getRange(e+d).select()}else e=document.getElementById("settingsLanguage").value,"excelPredefined"===e&&(e=Office.context.displayLanguage),"it-IT"===e?app.showNotification("Cella sbagliata. Seleziona una cella dalla colonna 'QueryAccount'."):"de-DE"===e?app.showNotification("Falsche Zelle. W\u00e4hlen Sie eine Zelle aus der Spalte 'QueryAccount'."):"fr-FR"===e?app.showNotification("Mauvaise cellule. S\u00e9lectionnez une cellule dans la colonne 'QueryAccount'."):
app.showNotification("Wrong cell. Select a cell from the 'QueryAccount' column.");uncheckAll("select-all-div");uncheckAll("slct2")})})["catch"](function(a){log(a,2)})}
function generateWorksheetContent(){var a=$("#ListBox").val(),b=$("#slctHeader").val();Excel.run(function(c){app.clearNotification();var f=c.workbook.worksheets.getActiveWorksheet();f.load("name");return c.sync().then(function(){"predefinedHeader"===b?generateHeader(c,f,a):generateEmptyHeader(c,f,a);var e=settings.settingsLanguage;"excelPredefined"===e&&(e=Office.context.displayLanguage);"it-IT"===e?log("Intestazione creata con successo.",1):"de-DE"===e?log("\u00dcberschrift erfolgreich erstellt.",
1):"fr-FR"===e?log("En-t\u00eate cr\u00e9\u00e9 avec succ\u00e8s.",1):log("Header successfully created.",1);f.activate()})}).then(function(){})["catch"](function(a){app.showNotification("Error","Something went wrong: "+a);log("Error: "+a,2)})}
function generateHeader(a,b,c){return a.sync().then(function(){b.getRange("A1:AZ13").clear();b.getRange("A1").values="QueryStart";b.getRange("A1").format.font.bold=!0;b.getRange("A2").values="QueryColumn";b.getRange("A3").values="File name";b.getRange("A4").values="Type";b.getRange("A5").values="Column";b.getRange("A6").values="Segment";b.getRange("A7").values="Start date";b.getRange("A8").values="End date";b.getRange("A9").values="Period Begin";b.getRange("A10").values="Period End";b.getRange("A11").values=
"Currency";b.getRange("A12").values="Header Left";b.getRange("A13").values="Header Right";b.getRange("A2").format.font.bold=!0;b.getRange("B2").values="QueryOptions";b.getRange("B2").format.font.bold=!0;b.getRange("B11").values="repeat";b.getRange("B12").values="repeat";b.getRange("B13").values="repeat";b.getRange("C3").values=c;b.getRange("C4").values="Column";b.getRange("C5").values="Group";b.getRange("D4").values="Column";b.getRange("D5").values="Account";b.getRange("E4").values="Column";b.getRange("E5").values=
"Description";b.getRange("F4").values="Current";b.getRange("F5").values="Opening";b.getRange("F7").values="";b.getRange("G4").values="Current";b.getRange("G5").values="Amount";b.getRange("G7").values="";b.getRange("G8").values="";b.getRange("A15").values="QueryAccount";b.getRange("B15").values="QueryOptions";b.getRange("A15:AZ15").format.font.bold=!0;b.getRange("A16").select()}).then(a.sync)}
function generateEmptyHeader(a,b,c){return a.sync().then(function(){b.getRange("A1:AZ13").clear();b.getRange("A1").values="QueryStart";b.getRange("A1").format.font.bold=!0;b.getRange("A2").values="QueryColumn";b.getRange("A3").values="File name";b.getRange("A4").values="Type";b.getRange("A5").values="Column";b.getRange("A6").values="Segment";b.getRange("A7").values="Start date";b.getRange("A8").values="End date";b.getRange("A9").values="Period Begin";b.getRange("A10").values="Period End";b.getRange("A11").values=
"Currency";b.getRange("A12").values="Header Left";b.getRange("A13").values="Header Right";b.getRange("A2").format.font.bold=!0;b.getRange("B2").values="QueryOptions";b.getRange("B2").format.font.bold=!0;b.getRange("A15").values="QueryAccount";b.getRange("B15").values="QueryOptions";b.getRange("A15:AZ15").format.font.bold=!0;b.getRange("A16").select()}).then(a.sync)}function createRange(a,b,c,f){return EXCEL_COLUMNS[b]+a+":"+EXCEL_COLUMNS[f]+c}
function updateTables(){checkErrors();var a=settings.settingsLanguage;if(ERROR_CONNECTION)"excelPredefined"===a&&(a=Office.context.displayLanguage),"it-IT"===a?(app.showNotificationError("Impossibile connettersi al web server locale. Server URL non corretto o Banana Contabilit\u00e0/web server non in esecuzione."),log("Impossibile connettersi al web server locale. Server URL non corretto o Banana Contabilit\u00e0/web server non in esecuzione.",2)):"de-DE"===a?(app.showNotificationError("Verbindung zum lokalen Webserver kann nicht hergestellt werden. Falscher URL-Server oder Banana Buchhaltung/Webserver nicht ausgef\u00fchrt."),
log("Verbindung zum lokalen Webserver kann nicht hergestellt werden. Falscher URL-Server oder Banana Buchhaltung/Webserver nicht ausgef\u00fchrt.",2)):"fr-FR"===a?(app.showNotificationError("Impossible de se connecter au serveur web local. Serveur URL incorrect ou Banana Comptabilit\u00e9/serveur web ne fonctionnent pas."),log("Impossible de se connecter au serveur web local. Serveur URL incorrect ou Banana Comptabilit\u00e9/serveur web ne fonctionnent pas.",2)):(app.showNotificationError("Cannot connect to local web server. Incorrect URL server or Banana Accounting/web server are not running."),
log("Cannot connect to local web server. Incorrect URL server or Banana Accounting/web server are not running.",2));else if(ERROR_READING_BANANA)"excelPredefined"===a&&(a=Office.context.displayLanguage),"it-IT"===a?(app.showNotificationError("Errore lettura dati da Banana Contabilit\u00e0. Nessun file aperto in Banana 9."),log("Errore lettura dati da Banana Contabilit\u00e0. Nessun file aperto in Banana 9.",2)):"de-DE"===a?(app.showNotificationError("Datenlesefehler von Banana Buchhaltung. Keine offene Datei in Banana 9."),
log("Datenlesefehler von Banana Buchhaltung. Keine offene Datei in Banana 9.",2)):"fr-FR"===a?(app.showNotificationError("Erreur de lecture des donn\u00e9es de Banana Comptabilit\u00e9. Aucun fichier n'est ouvert dans Banana 9."),log("Erreur de lecture des donn\u00e9es de Banana Comptabilit\u00e9. Aucun fichier n'est ouvert dans Banana 9.",2)):(app.showNotificationError("Error reading data from Banana Accounting. No file is open in Banana 9."),log("Error reading data from Banana Accounting. No file is open in Banana 9.",
2));else{document.getElementById("loader").style.display="block";app.clearNotification();var b=[],c={},f=[],e=[],d={},g={},k=[],l=[],n={},m=[],p=[],h=new OfficeExtension.Promise(function(a,b){a(null)});b.push(createRange(3,2,8,25));b.push(createRange(3,26,8,51));l.push(createRange(11,1,13,1));a=b.length;for(var r=0;r<a;r++)(function(a){h=h.then(function(){return readDataFromColumns(c,f,b[a],g,l,n)})})(r);h=h.then(function(){var a=16+g.cellCount;for(b=16;b<a;b+=10)e.push(createRange(b,0,b+10-1,0)),
m.push(createRange(b,1,b+10-1,1));for(var b=0;b<e.length;b++)a=e[b].split(":")[0].match(/([A-Za-z]+)([0-9]+)/),k.push(parseInt(a[2]))});h=h.then(function(){for(var a=e.length,b=0;b<a;b++)(function(a){h=h.then(function(){return readQueryAccount(d,e[a],m[a],k[a])});h=h.then(function(){return readDataFromBanana(d,f,k[a],p)})})(b);h=h.then(function(){return writeDataInExcel(f,p,n)})})}}
function readDataFromColumns(a,b,c,f,e,d){return Excel.run(function(g){var k=g.workbook.worksheets.getActiveWorksheet();k.load("name");var l=k.getRange(c);l.load("address, values");var n=k.getRange(e[0]);n.load("address, values");var m=k.getRange(RANGE_QUERYACCOUNT).getUsedRange();m.load("cellCount");return g.sync().then(function(){var c=n.values[1],e=n.values[2];d.currency=n.values[0].toString();d.headerLeft=c.toString().toLowerCase();d.headerRight=e.toString().toLowerCase();c="";e=l.values[0].length;
for(var g=0;g<e;g++){a[g]={file:l.values[0][g],type:l.values[1][g].toLowerCase(),column:l.values[2][g].toLowerCase(),segment:l.values[3][g],startdate:l.values[4][g],enddate:l.values[5][g]};var k=l.address.split("!")[1].match(/([A-Za-z]+)([0-9]+)/)[1];1===k.length?a[g].columnIndex=String.fromCharCode(k.charCodeAt(0)+g):2===k.length&&(a[g].columnIndex=k.charAt(0)+String.fromCharCode(k.charCodeAt(1)+g));a[g].file&&a[g].file!==c&&"p"!==a[g].file.substring(0,1)&&-1<a[g].file.indexOf(".ac2")?c=a[g].file:
a[g].file!==c&&a[g].file?a[g].file!==c&&"p"===a[g].file.substring(0,1)&&0>a[g].file.indexOf(".ac2")&&(c=c.replace(/_p[0-9]/g,""),k=a[g].file.substring(1),a[g].file=c+"_p"+k,c=a[g].file):a[g].file=c;a[g].basiccurrency=info(c,"AccountingDataBase","BasicCurrency");a[g].headerleft=info(c,"Base","HeaderLeft");a[g].headerright=info(c,"Base","HeaderRight");b.push(a[g]);f.cellCount=m.cellCount}})})["catch"](function(a){})}
function readQueryAccount(a,b,c,f){return Excel.run(function(e){var d=e.workbook.worksheets.getActiveWorksheet();d.load("name");var g=d.getRange(b);g.load("address, values");var k=d.getRange(c);k.load("address, values");return e.sync().then(function(){for(var b=f,c=g.values.length,d=0;d<c;d++)a[d]={address:"A"+b,text:g.values[d],queryoptions:k.values[d].toString().toLowerCase().trim()},b++})})["catch"](function(a){})}
function readDataFromBanana(a,b,c,f){return Excel.run(function(e){return e.sync().then(function(){for(var d in a){var e=a[d].text,k=a[d].queryoptions;if(""!=e)for(var l=b.length,n=0;n<l;n++){var m=b[n].file,p=b[n].type,h=b[n].column,r=b[n].segment,u=b[n].startdate,v=b[n].enddate,t=b[n].columnIndex;if("column"===p)h="fiscalnumber"===h?"FiscalNumber":"bclass"===h?"BClass":"budgetdifference"===h?"BudgetDifference":"priordifference"===h?"PriorDifference":"budgetprior"===h?"BudgetPrior":"periodbegin"===
h?"PeriodBegin":"perioddebit"===h?"PeriodDebit":"periodcredit"===h?"PeriodCredit":"periodtotal"===h?"PeriodTotal":"periodend"===h?"PeriodEnd":"nameprefix"===h?"NamePrefix":"firstname"===h?"FirstName":"familyname"===h?"FamilyName":"organisationname"===h?"OrganisationName":"addressextra"===h?"AddressExtra":"pobox"===h?"POBox":"postalcode"===h?"PostalCode":"countrycode"===h?"CountryCode":"phonemain"===h?"PhoneMain":"phonemobile"===h?"PhoneMobile":"emailwork"===h?"EmailWork":"dateofbirth"===h?"DateOfBirth":
"paymenttermindays"===h?"PaymentTermInDays":"creditlimit"===h?"CreditLimit":"memberfee"===h?"MemberFee":"bankname"===h?"BankName":"bankiban"===h?"BankIban":"bankaccount"===h?"BankAccount":"bankclearing"===h?"BankClearing":h.charAt(0).toUpperCase()+h.slice(1),p=accountDescription(m,e,h).trim(),m=c+parseInt(d),f.push({col:t,row:m,value:p});else if("columnvat"===p)h="vatcode"===h?"VatCode":"isdue"===h?"IsDue":"amounttype"===h?"AmountType":"vatrate"===h?"VatRate":"vatrateongross"===h?"VatRateOnGross":
"vatpercentnondeductible"===h?"VatPercentNonDeductible":"vataccount"===h?"VatAccount":h.charAt(0).toUpperCase()+h.slice(1),p=vatDescription(m,e,h).trim(),m=c+parseInt(d),f.push({col:t,row:m,value:p});else if("current"===p||"budget"===p){convertPeriod(m,b[n],u,v);"$"===e.toString().substring(0,1)&&(e=getAccountsList(m,e.toString()).join("|"),-1<e.indexOf("Gr=")&&(e=e.replace(/Gr=/g,""),e="Gr="+e));if("current"===p)var q=currentBalance(m,e+r,b[n].formattedString);else"budget"===p&&(q=budgetBalance(m,
e+r,b[n].formattedString));"invert"===k&&q[h]&&"bclass"!==h&&"enddate"!==h&&"periodstring"!==h&&"rowcount"!==h&&"startdate"!==h?p=-1*q[h]:"budget"===k?(q=budgetBalance(m,e+r,b[n].formattedString),p=q[h]):"budgetinvert"===k&&q[h]&&"bclass"!==h&&"enddate"!==h&&"periodstring"!==h&&"rowcount"!==h&&"startdate"!==h?(q=budgetBalance(m,e+r,b[n].formattedString),p=-1*q[h]):p=q[h];""===p&&(p=0);m=c+parseInt(d);f.push({col:t,row:m,value:p})}else"currentvat"===p&&(convertPeriod(m,b[n],u,v),"$"===e.toString().substring(0,
1)&&"$"===e.toString().substring(0,1)&&(e=getVatCodesList(m,e.toString()).join("|")),q=vatCurrentBalance(m,e,b[n].formattedString),p=q[h],""===p&&(p=0),m=c+parseInt(d),f.push({col:t,row:m,value:p}))}}})["catch"](function(a){})})["catch"](function(a){})}
function writeDataInExcel(a,b,c){return Excel.run(function(f){var e=f.workbook.worksheets.getActiveWorksheet();e.load("name");return f.sync().then(function(){updateProperties(a,c);for(var d=a.length,f=0;f<d;f++)if(""!==a[f].type&&""!==a[f].column){e.getRange(a[f].columnIndex+"9").values=a[f].formattedStartDate;e.getRange(a[f].columnIndex+"10").values=a[f].formattedEndDate;e.getRange(a[f].columnIndex+"11").values=a[f].basiccurrency;e.getRange(a[f].columnIndex+"12").values=a[f].headerleft;e.getRange(a[f].columnIndex+
"13").values=a[f].headerright;var k=a[f].column;k=k.charAt(0).toUpperCase()+k.slice(1);e.getRange(a[f].columnIndex+"15").values=k;e.getRange("A15:AZ15").format.font.bold=!0}d=b.length;for(f=0;f<d;f++)e.getRange(b[f].col+b[f].row).values=b[f].value;var l=new Date;d=l.getDate();f=l.getMonth()+1;k=l.getFullYear();var n=l.getHours(),m=l.getMinutes();l=l.getSeconds();9>=d&&(d="0"+d);9>=f&&(f="0"+f);9>=n&&(n="0"+n);9>=m&&(m="0"+m);9>=l&&(l="0"+l);e.getRange("C1").values="Last update: "+d+"."+f+"."+k+", "+
n+":"+m+":"+l})}).then(function(){document.getElementById("loader").style.display="none";var a=document.getElementById("settingsLanguage").value;"excelPredefined"===a&&(a=Office.context.displayLanguage);"it-IT"===a?(app.showNotification("Foglio di lavoro aggiornato correttamente."),log("Foglio di lavoro aggiornato correttamente.",1)):"de-DE"===a?(app.showNotification("Arbeitsblatt erfolgreich aktualisiert."),log("Arbeitsblatt erfolgreich aktualisiert.",1)):"fr-FR"===a?(app.showNotification("Feuille de calcul mise \u00e0 jour r\u00e9ussie."),
log("Feuille de calcul mise \u00e0 jour r\u00e9ussie.",1)):(app.showNotification("Worksheet successfully updated."),log("Worksheet successfully updated.",1))})["catch"](function(a){app.showNotification("Error update","Something went wrong: "+a);log("Error update: "+a,2)})}
function getVatCodesList(a,b){var c=b.substring(b.lastIndexOf("$")+1,b.lastIndexOf("=")).trim(),f=b.substr(b.indexOf("=")+1).trim(),e=[],d=tableVatCodes(a),g;for(g in d)if(d[g][c])for(var k=d[g][c].split(";"),l=0;l<k.length;l++)k[l]===f&&d[g].VatCode&&e.push(d[g].VatCode);return e}
function getAccountsList(a,b){var c=b.substring(b.lastIndexOf("$")+1,b.lastIndexOf("=")).trim(),f=b.substr(b.indexOf("=")+1).trim(),e=[],d=tableAccounts(a),g;for(g in d)if(d[g][c])for(var k=d[g][c].split(";"),l=0;l<k.length;l++)k[l]===f&&(d[g].Account?e.push(d[g].Account):d[g].Group&&e.push("Gr="+d[g].Group));return e}
function updateProperties(a,b){for(var c=1;c<a.length;c++)"norepeat"===b.currency&&a[c].file===a[c-1].file&&(a[c].basiccurrency=""),"norepeat"===b.headerLeft&&a[c].file===a[c-1].file&&(a[c].headerleft=""),"norepeat"===b.headerRight&&a[c].file===a[c-1].file&&(a[c].headerright="")}
function convertPeriod(a,b,c,f){3<c.toString().length&&3<f.toString().length?(0>c.toString().indexOf(".")&&0>f.toString().indexOf(".")?(f=new Date(Math.round(864E5*(f-25569))),c=(new Date(Math.round(864E5*(c-25569)))).toISOString().slice(0,10),f=f.toISOString().slice(0,10)):(c=c.split("."),c=(new Date(c[2]+"-"+c[1]+"-"+c[0])).toISOString().slice(0,10),f=f.split("."),f=(new Date(f[2]+"-"+f[1]+"-"+f[0])).toISOString().slice(0,10)),b.formattedStartDate=c,b.formattedEndDate=f,b.formattedString=c+"/"+
f):(c=c.toUpperCase(),""!=c?(b.formattedStartDate=startperiod(a,c),b.formattedEndDate=endperiod(a,c),b.formattedString=c):(b.formattedStartDate=startperiod(a,"ALL"),b.formattedEndDate=endperiod(a,"ALL"),b.formattedString="ALL"))}
function openTab(a,b){var c;var f=document.getElementsByClassName("tabcontent");for(c=0;c<f.length;c++)f[c].style.display="none";f=document.getElementsByClassName("tablinks");for(c=0;c<f.length;c++)f[c].className=f[c].className.replace(" active","");document.getElementById(b).style.display="block";a.currentTarget.className+=" active";app.clearNotification()}function selectAll(a){for(var b=document.querySelectorAll('input[type="checkbox"]'),c=0;c<b.length;c++)b[c]!=a&&(b[c].checked=a.checked)}
function uncheckAll(a){a=document.querySelectorAll("#"+a+' input[type="checkbox"]');for(var b=0;b<a.length;b++){var c=a[b];c.disabled||(c.checked=!1)}}function createTestCurrent(){Excel.run(function(a){var b=a.workbook.worksheets.getActiveWorksheet().load("name");a.workbook.worksheets.load("name");return a.sync().then(function(){var a=b.name;0>a.indexOf(SUBSTRING_FILE_NAME_TEST)?duplicateSheet(a):testlog("Wrong worksheet selected.")})})["catch"](function(a){app.showNotification(a);testlog(a)})}
function createTestAll(){Excel.run(function(a){var b=a.workbook.worksheets.load("name");return a.sync().then(function(){for(var a=0;a<b.items.length;a++)0>b.items[a].name.indexOf(SUBSTRING_FILE_NAME_TEST)&&duplicateSheet(b.items[a].name)})})["catch"](function(a){testlog(a)})}
function duplicateSheet(a){Excel.run(function(b){var c=b.workbook.worksheets.getItem(a).getUsedRange();c.load("values");c.load("address");var f=b.workbook.worksheets.add(a+SUBSTRING_FILE_NAME_TEST);return b.sync().then(function(){var a=c.address.substring(c.address.indexOf("!")+1);f.getRange(a).values=c.values}).then(b.sync)})["catch"](function(a){testlog(a)})}
function test(){return Excel.run(function(a){var b=a.workbook.worksheets.load("name");return a.sync().then(function(){for(var a=0;a<b.items.length;a++)if(-1<b.items[a].name.indexOf(SUBSTRING_FILE_NAME_TEST)){var f=b.items[a].name.replace(SUBSTRING_FILE_NAME_TEST,"");testWorksheet(f)}})})["catch"](function(a){testlog(a)})}
function testWorksheet(a){Excel.run(function(b){app.clearNotification();var c=!1,f=2,e=b.workbook.worksheets.getItem(a).getRange(RANGE_WORKSHEET).getUsedRange();e.load("address, values, cellCount");var d=b.workbook.worksheets.getItem(a+SUBSTRING_FILE_NAME_TEST).getRange(RANGE_WORKSHEET).getUsedRange();d.load("address, values, cellCount");return b.sync().then(function(){var g=e.values.length,k=d.values.length;g=g>=k?g:k;testlog("..."+a+" test begin...");testlog("Rows to test: "+g);for(k=0;k<g;k++)try{for(var l=
e.values[k],n=d.values[k],m=0;m<l.length;m++)l[m].toString()!==n[m].toString()&&(testlog("Cell "+EXCEL_COLUMNS[m]+f+" : "+a+" '"+l[m]+"', "+a+"_test_expected '"+n[m]+"'"),b.workbook.worksheets.getItem(a).getRange(EXCEL_COLUMNS[m]+f).format.font.color="Red",c=!0);f++}catch(p){}c||testlog(a+": No differences found.");testlog("..."+a+" test end...");testlog("********************")})}).then(function(){app.showNotification("Test successfully executed: check LOGS for details.")})["catch"](function(a){app.showNotification("Error test()",
"Something went wrong: "+a);testlog("Error: "+a)})}function deleteActiveWorksheet(){Excel.run(function(a){a.workbook.worksheets.getActiveWorksheet()["delete"]();return a.sync()})["catch"](function(a){testlog("Error: "+a)})}function checkDevsPassword(){"banana9"===document.getElementById("devsTestSettings").value?document.getElementById("test").style.display="block":document.getElementById("test").style.display="none";document.getElementById("devsTestSettings").value=""};